//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSGYMProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiscalyear
    {
        public int Fid { get; set; }
        public Nullable<System.DateTime> FiscalyearFromDate { get; set; }
        public Nullable<System.DateTime> FiscalyearToDate { get; set; }
        public string Year { get; set; }
    }
}
