//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSGYMProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRegistration
    {
        public long MemID { get; set; }
        public string MemberNo { get; set; }
        public string MemberFName { get; set; }
        public string MemberLName { get; set; }
        public string MemberMName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Age { get; set; }
        public string Contactno { get; set; }
        public string EmailID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> PlantypeID { get; set; }
        public Nullable<int> WorkouttypeID { get; set; }
        public Nullable<long> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string MemImagename { get; set; }
        public string MemImagePath { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Address { get; set; }
        public Nullable<long> MainMemberID { get; set; }
    }
}
