//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSGYMProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public long ReceiptID { get; set; }
        public Nullable<long> Memberid { get; set; }
        public Nullable<long> generateby { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
